name = "unfold"
uuid = "181c99d8-e21b-4ff3-b70b-c233eddec679"
authors = ["Benedikt Ehinger <behinger@uos.de>"]
version = "0.1.0"

[deps]
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
