name: Run benchmarks

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: Install registered dependencies
        uses: julia-actions/julia-buildpkg@latest
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI@0.1"'
      - name: Run benchmarks
        run: julia --project=. -e 'using BenchmarkCI; BenchmarkCI.judge()'
      - name: Post results
        run: julia --project=. -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
