# This is a basic workflow to help you get started with Actions
name: CI
     
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.4.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - run: pwd
      - name: setup julia
        uses: julia-actions/setup-julia@v1.1
        with:
          version: 1.3.0
      - name: Install dependencies
        uses: julia-actions/julia-buildpkg@master
        #run: julia --project=test -e 'using Pkg; Pkg.instantiate()'
      - uses: julia-actions/julia-runtest@master
     # - name: Build and deploy
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #     DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
     #   run: julia --project=docs --color=yes docs/make.jl
